# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kaygalle/CLionProjects/PerlinNoise

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kaygalle/CLionProjects/PerlinNoise

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaygalle/CLionProjects/PerlinNoise/CMakeFiles /home/kaygalle/CLionProjects/PerlinNoise/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kaygalle/CLionProjects/PerlinNoise/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named PerlinNoise

# Build rule for target.
PerlinNoise: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PerlinNoise
.PHONY : PerlinNoise

# fast build rule for target.
PerlinNoise/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/build
.PHONY : PerlinNoise/fast

PPM/PPM.o: PPM/PPM.cpp.o

.PHONY : PPM/PPM.o

# target to build an object file
PPM/PPM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PPM/PPM.cpp.o
.PHONY : PPM/PPM.cpp.o

PPM/PPM.i: PPM/PPM.cpp.i

.PHONY : PPM/PPM.i

# target to preprocess a source file
PPM/PPM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PPM/PPM.cpp.i
.PHONY : PPM/PPM.cpp.i

PPM/PPM.s: PPM/PPM.cpp.s

.PHONY : PPM/PPM.s

# target to generate assembly for a file
PPM/PPM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PPM/PPM.cpp.s
.PHONY : PPM/PPM.cpp.s

PerlinNoise.o: PerlinNoise.cpp.o

.PHONY : PerlinNoise.o

# target to build an object file
PerlinNoise.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PerlinNoise.cpp.o
.PHONY : PerlinNoise.cpp.o

PerlinNoise.i: PerlinNoise.cpp.i

.PHONY : PerlinNoise.i

# target to preprocess a source file
PerlinNoise.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PerlinNoise.cpp.i
.PHONY : PerlinNoise.cpp.i

PerlinNoise.s: PerlinNoise.cpp.s

.PHONY : PerlinNoise.s

# target to generate assembly for a file
PerlinNoise.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/PerlinNoise.cpp.s
.PHONY : PerlinNoise.cpp.s

example.o: example.cpp.o

.PHONY : example.o

# target to build an object file
example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/example.cpp.o
.PHONY : example.cpp.o

example.i: example.cpp.i

.PHONY : example.i

# target to preprocess a source file
example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/example.cpp.i
.PHONY : example.cpp.i

example.s: example.cpp.s

.PHONY : example.s

# target to generate assembly for a file
example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PerlinNoise.dir/build.make CMakeFiles/PerlinNoise.dir/example.cpp.s
.PHONY : example.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... PerlinNoise"
	@echo "... PPM/PPM.o"
	@echo "... PPM/PPM.i"
	@echo "... PPM/PPM.s"
	@echo "... PerlinNoise.o"
	@echo "... PerlinNoise.i"
	@echo "... PerlinNoise.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

